### ISSUE TITLE
output file

### ISSUE THREAD

**Issue by khchuang** [zhfkt/ComplexCi#1]
Hi, there is another output file named xxx.fmt. Could you explain what the numbers represent? Besides, I want to know the giant component ratio when removing each hub in the xxx_out file. Is there a way to export that info?

**Comment by zhfkt** [comment]
Hi Khchuang,

1. For the first question

> Hi, there is another output file named xxx.fmt. Could you explain what the numbers represent?

For the file xxx.fmt, it is the adjacency list input file for the original CI algorithm CI_HEAP  (Morone F, Min B, Bo L, et al. Collective Influence Algorithm to find influencers via optimal percolation in massively large social media[J]. Scientific reports, 2016, 6.) code provided on the  http://www-levich.engr.ccny.cuny.edu/~hernanlab/uploads/CI_HEAP.c . It seems that this link can not be accessed now .  You can check the details of CI_HEAP  in this repo and I upload a slightly modified version on the following link: 
  https://github.com/zhfkt/ComplexCi/blob/292ae4ad9a9e6ae7992bf107b43d0da7f06d1d93/ComplexCi/CI_HEAP.cpp#L16

//      - network file must be an adjacency list where the first number on each line is a node ID and the following numbers on that line are its neighbors, e.g.:
//      1 3255 18210 24119 70247
//      2 9205 88665 89859
//      3 3255 328244 25046 41508
//      …
//      3255 1 3 34913 73168 

The inputs for the current ComplexCI and original CI_HEAP are different. In order to run the original CI algorithm CI_HEAP , I need to transform the inputs of ComplexCI  to the CI_HEAP , which is the xxx.fmt file you see in the output.


2. For the second question:

> Besides, I want to know the giant component ratio when removing each hub in the xxx_out file. Is there a way to export that info?

I was using the metric code of Robustness from DataCastle Competition in the http://share.pkbigdata.com/ID.4407/Master_algorithm . There is also a modified version Master_algorithm for the common network in this repo. I didn't implement calculating the giant component ratio myself when removing each hub in the xxx_out file,  because the algorithm in this repo was developed and verified when I participated in the DataCastle Competition and I just used the ready-made version . It seems that the current Master_algorithm code can only give the Robustness score according to the remove order. If you would like to check the giant component ratio for each removed hub,  you may modified the groovy code file https://github.com/zhfkt/ComplexCi/blob/master/Master_algorithm/src/main/java/org/dc/algorithm/NetMaster.groovy  for your demand.

Thank you
